In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = []
# Using a loop to square each element (slow)
for num in arr:
 result.append(num ** 2)
print(result) # Output: [1, 4, 9, 16, 25]

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [ ]:
# Vectorization allows you to perform operations on entire arrays at once, instead of
# iterating over elements one by one. This is made possible by NumPy’s optimized
# C-based backend that executes operations in compiled code, which is much faster
# than Python loops.

In [4]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 # Vectorized operation
print(result) # Output: [1 4 9 16 25]

[ 1  4  9 16 25]


In [ ]:
# Why is it Faster?
# Low-level implementation: NumPy’s vectorized operations are implemented
# in C (compiled language), which is much faster than Python loops.
# Batch processing: NumPy processes multiple elements in parallel using SIMD
# (Single Instruction, Multiple Data), allowing multiple operations to be done
# simultaneously.

In [5]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10 # Broadcasting: 10 is added to all elements
print(result) # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2 # Element-wise addition
print(result) # Output: [11 22 33]

[11 22 33]


In [7]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2 # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
# [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [ ]:
# Imagine you have a dataset where each row represents a sample and each column
# represents a feature. You can normalize the data by subtracting the mean of each
# column and dividing by the standard deviation
# In this case, broadcasting allows you to subtract the mean and divide by the
# standard deviation for each feature without needing loops or creating copies of the
# data

In [8]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
