In [2]:
import numpy as np

In [3]:
!pip install numpy

In [4]:
arr=np.array([1,2,3]) #Way1 of making numpy

In [5]:
arr

array([1, 2, 3])

In [9]:
arr1=np.array([1,2,3]) #1D array
arr2=np.array([[1,2,3],[3,4,5],[6,6,7]]) #2D array
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [3 4 5]
 [6 6 7]]


In [12]:
np.zeros((3,3))  ## Zeroes filled array of 3 rows 3 columns
#argument is tuple

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((4,6),5)   #(shape,value)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [15]:
np.eye(5)    # Gives identity matrix with nxn dimensions here 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(1,100,9)  #Like range where 1 to 100 or n it will go with 9 as gap

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [17]:
np.linspace(1,100,5) #equally spaced from 1 to 100 along with length of array

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [21]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [22]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
myarr.shape #Gives the dimesnions mxn

(4, 3)

In [24]:
myarr.size  #Gives total elements

12

In [25]:
myarr.ndim   # 2 means 2 Dimensional

2

In [26]:
myarr.dtype   #default data type either int32 or int 64

dtype('int64')

In [ ]:
#HOW  

In [33]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float32')

In [36]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [34]:
n=myarr.astype('float64')  #astype is the keyword used to change datatype

In [35]:
n.dtype

dtype('float64')

In [46]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [47]:
myarr.shape

(4, 3)

In [50]:
myarr.reshape((3,4)) #can be reshaped just nxm=size must remain same

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
myarr.flatten() #We recieve a 1D array now

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])