In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [5]:
flat=arr.flatten()

In [6]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat[0]  #indexing

np.int64(1)

In [9]:
flat[3]  #indexing

np.int64(4)

In [10]:
flat[3:6] #slicing

array([4, 5, 6])

In [11]:
flat[:5]  #Same as 0->4th index

array([1, 2, 3, 4, 5])

In [12]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
flat[::2]  #every second element

array([ 1,  3,  5,  7,  9, 12])

In [ ]:
#Slicing returns a view, not a copy! Changes affect the original array.**


In [14]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [15]:
b=flat[3:7]

In [16]:
b

array([4, 5, 6, 7])

In [17]:
b[0]=444444 #changes in b

In [18]:
b 

array([444444,      5,      6,      7])

In [19]:
flat #leads to changes in flat since it is a view to the same memory location

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [21]:
#To make copy use .copy() ....this is not slice
b=flat[3:7].copy()

In [22]:
b[0]=22222222

In [23]:
b

array([22222222,        5,        6,        7])

In [24]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [36]:
#Fancy Indexing
arr1=np.array([10,20,30,40,50])
print(arr[[0,1,2]])


[10 20 30]


In [37]:
#Boolean Masking
arr2=np.array([10,12,13,344,43])
mask=arr2>12  #ek condition 
print(arr2[mask])

[ 13 344  43]


In [ ]:
#PRACTICE QUESTIONS
#The working of np.random.rand(),np.random.randint(),np.random.randn(),np.random.uniform()

In [62]:
new_arr=np.random.rand(3,3)  #(Most common)
new_arr                #Generates random number btw 0 and 1 argument is shape

array([[0.07557877, 0.50882951, 0.51598909],
       [0.6538201 , 0.13129378, 0.98962059],
       [0.87567192, 0.08079721, 0.66998448]])

In [66]:
new_arr2=np.random.randint(1,100,(3,3))
new_arr2
#Random integers btw start and end and shape also given

array([[83, 78, 66],
       [70, 57, 74],
       [66, 65,  1]], dtype=int32)

In [68]:
new_arr3=np.random.random((3,3))
new_arr3
#Similar to random.rand

array([[0.14082947, 0.42192084, 0.74675439],
       [0.32508832, 0.86201471, 0.46666376],
       [0.37424449, 0.1922152 , 0.89231064]])

In [85]:
new_arr4=np.random.uniform(10,30,(3,3))
new_arr4
#generates random values btwen star and end

array([[15.76497184, 20.06182775, 13.39357597],
       [14.93333354, 22.29758546, 17.63528653],
       [13.31591999, 23.73924671, 20.89205636]])

In [94]:
new_arr5 = np.random.randn(3,3)
new_arr5
#Generates numbers from a normal (Gaussian) distribution.

array([[-0.19502207, -0.07798695, -0.47618865],
       [ 0.23540329,  0.04743426,  2.08452706],
       [-0.2049609 , -0.07377552, -0.36791364]])

In [96]:
#Q)Convert an array of floats [1.1,2.2,3.3] into integers.
new_arr6=np.array([1.1,2.2,3.3],dtype='int32')
new_arr6

array([1, 2, 3], dtype=int32)

In [100]:
#Q)Do Fancy indexing to extract even numbers from [1,2,3,4,5,6]
my_arr1=np.array([1,2,3,4,5,6])
idx=[1,3,5]
print(my_arr1[idx])

[2 4 6]


In [103]:
#Q)Reshape a 1D array of size 9 to 3x3 matrix
this_arr=np.array([1,2,3,4,5,6,7,8,9])
this_arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])