In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],
[4,5,6],
[7,8,9]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

array([1, 2, 3])

In [14]:
arr.sum(axis=0) #when axis=0 then sum down the rows

array([12, 15, 18])

In [15]:
arr.sum(axis=1) #when axis=1 then sum across the columns

array([ 6, 15, 24])

In [ ]:
# axis=0  → work column-wise (go down)
# axis=1  → work row-wise (go across)
# print(arr.sum(axis=0))
# print(arr.sum(axis=1))
# print(arr.mean(axis=0))
# print(arr.mean(axis=1))
# print(arr.max(axis=0))
# print(arr.max(axis=1))
# similarly above can be done

In [16]:
#Multidimensional indexing
arr[0,1] #0th row and 1st column

np.int64(2)

In [17]:
arr[0:2,1:3] #Means-> 0th and 1st row and 1st and 2nd column

array([[2, 3],
       [5, 6]])

In [18]:
#Indexing in 3D arrays
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [19]:
print(arr3D.shape)  #depth ,row, column

(2, 2, 3)


In [20]:
print(arr3D[0, 1, 2]) #pehla 2d array mai 1st row and 2nd column

6


In [30]:
print(arr3D[:, 0, :])   # Get the first row from both sheets
#saare 2d arrays but 1st row and saare columns

[[1 2 3]
 [7 8 9]]


In [32]:
# Get all rows of the first column
arr3D[:,:,0]

array([[ 1,  4],
       [ 7, 10]])

In [35]:
# Replace all elements in column 1 with 0
arr[:,1]=0
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])