In [ ]:
##SPEED

In [22]:
#Using Python Lists:
import numpy as np
import time

size=1_000_000
    
# range basically creates a list of 0 to size-1 elements like 0,1,2..
l1=list(range(size))
l2=list(range(size))

start=time.time() #starting a stop watch 
add=[x+y for x,y in zip(l1,l2)]
end=time.time()
print("Python Lists take",end-start)


Python Lists take 0.17522192001342773


In [21]:
#Using Numpy Arrays:
import numpy as np
import time

size=1_000_000

#One way of creating Numpy array(np.array( ke andar list daldo)
l1=np.array(range(size))
l2=np.array(range(size))

start=time.time() #starting a stop watch 
add=l1+l2
end=time.time()
print("Python Lists take",end-start)


Python Lists take 0.011064529418945312


In [23]:
l1=[1,2,4] 
l2=[6,7,8]
list(zip(l1,l2)) # returns the tuple sequence wise

[(1, 6), (2, 7), (4, 8)]

In [24]:
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [24]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [25]:
np.array([1,2,3,4,5,"Kabir"]) #Dikkat
#Array numbers ka hi rehna chahiye

array(['1', '2', '3', '4', '5', 'Kabir'], dtype='<U21')

In [28]:
np.array([[1,2,3],[4,5,6]]) #Nested numpy array (It only takes 1 Argument)

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(arr))  #data structure of NumPy used to store numbers
arr.shape

<class 'numpy.ndarray'>


(3, 3)

In [37]:
## MEMORY

In [36]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

#nbytes gives: Number of elements × bytes per element

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [ ]:
##VECTORIZATION -NO MORE USE OF LOOPS

In [41]:
#Python Lists
list1=[1,2,3]
list_squares=[x**2 for x in list1]
print(list_squares)

#Numpy 
arr1=np.array([1,2,3])
numpy_squares=arr1**2
print(numpy_squares)

##Even syntax of numpy is simple.

[1, 4, 9]
[1 4 9]
